steps:
- name: "docker.io/library/python:3.12"
  id: CI
  entrypoint: /bin/sh
  args:
  - -c
  - 'chmod a+x install.sh && ./install.sh && pytest'

options:
  logging: CLOUD_LOGGING_ONLY
  logs_bucket: gs://purchase_predict