steps:
- name: "ghcr.io/astral-sh/uv:python3.12-bookworm"
  id: CI
  entrypoint: /bin/bash
  args:
  - -c
  - |
    chmod a+x install.sh && 
    ./install.sh &&
    source .venv/bin/activate && 
    gcloud auth print-access-token && 
    pytest .

logs_bucket: gs://purchase_predict
