steps:
- name: "noobzik/uv-gcp-cloud-build"
  id: CI
  entrypoint: /bin/bash
  env:
    - PROJECT_ID=$PROJECT_ID
    - SERVICE_ACCOUNT=$_SERVICE_ACCOUNT
  args:
  - -c
  - |
    gcloud config set project "$PROJECT_ID"
    chmod a+x install.sh && 
    ./install.sh &&
    source .venv/bin/activate &&
    pytest .
#- name: "noobzik/uv-gcp-cloud-build"
#  id: CD
#  entrypoint: /bin/bash
#  args:
#  - -c
#  - 'chmod a+x install.sh && ./install.sh && kedro run --pipeline global'
#  env:
#  - 'ENV=$BRANCH_NAME'
#  - 'MLFLOW_SERVER=$_MLFLOW_SERVER'

logs_bucket: gs://purchase_predict
