steps:
- name: "ghcr.io/astral-sh/uv:python3.13-bookworm"
  id: CI
  entrypoint: /bin/sh
  args:
  - -c
  - |
    chmod a+x install.sh && 
    ./install.sh &&
    source .venv/bin/activate && 
    pytest

logs_bucket: gs://purchase_predict
