test_ratio: 0.3
automl_max_evals: 1
gcp_project_id: esgi-352608
gcs_primary_folder: purchase_predict/primary.csv
mlflow_enabled: True
mlflow_experiment_id: 1
mlflow_model_registry: "purchase_predict" # Name of model registry of this project